// src/app/api/tickets/route.js

// src/app/api/tickets/route.js

export async function GET() {
  const tickets = [
    {
      id: "t-1023",
      title: "Cannot connect to VPN",
      description: "User reports intermittent VPN connectivity errors.",
      priority: "High",
      status: "Open",
      assignee: "Unassigned",
      updatedAt: "2025-10-31T14:05:00Z",
    },
    {
      id: "t-1024",
      title: "Email not syncing",
      description: "Mobile client is no longer receiving new emails.",
      priority: "Medium",
      status: "Open",
      assignee: "Jordan",
      updatedAt: "2025-11-01T09:32:00Z",
    },
    {
      id: "t-1025",
      title: "Password reset request",
      description: "User unable to complete self-service password reset.",
      priority: "Low",
      status: "Resolved",
      assignee: "Taylor",
      updatedAt: "2025-11-02T16:10:00Z",
    },
    {
      id: "t-1026",
      title: "CRM access denied",
      description: "Sales team member cannot access CRM after role change.",
      priority: "High",
      status: "In Progress",
      assignee: "Alex",
      updatedAt: "2025-11-03T11:45:00Z",
    },
    {
      id: "t-1027",
      title: "Print server offline",
      description: "Office printers not reachable from any subnet.",
      priority: "Critical",
      status: "Open",
      assignee: "Unassigned",
      updatedAt: "2025-11-04T08:15:00Z",
    },
    {
      id: "t-1028",
      title: "New hire onboarding",
      description: "Provision accounts and laptop for new hire starting Monday.",
      priority: "Medium",
      status: "On Hold",
      assignee: "Morgan",
      updatedAt: "2025-11-04T18:20:00Z",
    },
    {
      id: "t-1029",
      title: "Shared drive permissions",
      description: "Marketing folder access requested for contractor.",
      priority: "Low",
      status: "Open",
      assignee: "Casey",
      updatedAt: "2025-11-05T13:05:00Z",
    },
    {
      id: "t-1030",
      title: "Service outage post-mortem",
      description: "Compile notes and attach logs for incident INC-774.",
      priority: "Medium",
      status: "In Progress",
      assignee: "Riley",
      updatedAt: "2025-11-06T10:40:00Z",
    },
    {
      id: "t-1031",
      title: "Two-factor enrollment issue",
      description: "User's phone number not accepted during 2FA setup.",
      priority: "High",
      status: "Open",
      assignee: "Jamie",
      updatedAt: "2025-11-06T15:22:00Z",
    },
    {
      id: "t-1032",
      title: "Slow Wi-Fi on 3rd floor",
      description: "Reports of unstable connection near conference rooms.",
      priority: "Medium",
      status: "In Progress",
      assignee: "Alex",
      updatedAt: "2025-11-07T09:55:00Z",
    },
    {
      id: "t-1033",
      title: "License renewal check",
      description: "Verify remaining licenses for design tools.",
      priority: "Low",
      status: "On Hold",
      assignee: "Unassigned",
      updatedAt: "2025-11-07T17:30:00Z",
    },
    {
      id: "t-1034",
      title: "Database CPU alerts",
      description: "Spikes detected on primary DB during backups.",
      priority: "High",
      status: "Resolved",
      assignee: "Taylor",
      updatedAt: "2025-11-08T02:05:00Z",
    },
    {
      id: "t-1035",
      title: "Okta group cleanup",
      description: "Review and remove unused legacy groups.",
      priority: "Medium",
      status: "Open",
      assignee: "Morgan",
      updatedAt: "2025-11-08T11:18:00Z",
    },
    {
      id: "t-1036",
      title: "Laptop running hot",
      description: "Fan always at max after last OS update.",
      priority: "Low",
      status: "Open",
      assignee: "Casey",
      updatedAt: "2025-11-09T09:10:00Z",
    },
    {
      id: "t-1037",
      title: "Production API latency",
      description: "Increased response times from region us-east-1.",
      priority: "Critical",
      status: "In Progress",
      assignee: "Riley",
      updatedAt: "2025-11-09T11:45:00Z",
    },
  ];

  return Response.json(tickets);
}
